"use client";

import { FormEvent, useState } from "react";
import Link from "next/link";

type Access={_id:string;email:string;expiresAt:number;revokedAt?:number;createdAt:number;lastUsedAt?:number};

export default function PortalAccessAdminPage(){
  const[token,setToken]=useState("");const[email,setEmail]=useState("");const[requestId,setRequestId]=useState("");const[result,setResult]=useState<{portalPath:string;expiresAt:number}|null>(null);const[records,setRecords]=useState<Access[]>([]);const[error,setError]=useState("");
  async function load(){if(!requestId||!token)return;const r=await fetch(`/api/admin/portal-access?requestId=${encodeURIComponent(requestId)}`,{headers:{"x-admin-token":token},cache:"no-store"});const d=await r.json();if(!r.ok)return setError(d.error||"Unable to load access links.");setRecords(d.access??[]);}
  async function submit(e:FormEvent,revokeAccessId?:string){e.preventDefault();setError("");setResult(null);const r=await fetch("/api/admin/portal-access",{method:"POST",headers:{"Content-Type":"application/json","x-admin-token":token},body:JSON.stringify({email,travelRequestId:requestId,revokeAccessId})});const d=await r.json();if(!r.ok)return setError(d.error||"Unable to create access link.");setResult(d);await load();}
  async function revoke(id:string){const r=await fetch("/api/admin/portal-access",{method:"DELETE",headers:{"Content-Type":"application/json","x-admin-token":token},body:JSON.stringify({id})});if(!r.ok)return setError("Unable to revoke access link.");await load();}
  async function rotate(record:Access){setEmail(record.email);const event={preventDefault:()=>{}} as FormEvent;await submit(event,record._id);}
  return <main className="admin-shell"><div className="shell"><div className="admin-header"><div><Link href="/admin/overview" className="back-link">← Dashboard</Link><span className="eyebrow">Traveler access</span><h1>Secure portal access</h1></div></div><form className="cms-form" onSubmit={submit}><h2>Create or manage access</h2><label>Traveler email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Trip request ID<input value={requestId} onChange={e=>setRequestId(e.target.value)} onBlur={load} required/></label><label className="wide">Advisor passcode<input type="password" value={token} onChange={e=>setToken(e.target.value)} onBlur={load} required/></label><div className="wide cms-actions"><button className="button">Generate 7-day portal link</button><button type="button" className="ghost" onClick={load}>Refresh access list</button></div>{error&&<p className="error wide">{error}</p>}{result&&<div className="wide access-result"><strong>Traveler link created — copy it now</strong><code>{result.portalPath}</code><small>Expires {new Date(result.expiresAt).toLocaleString()}. The raw token is not stored and cannot be recovered later.</small></div>}</form>{records.length>0&&<div className="cms-list">{records.map(record=><article key={record._id}><div><small>{record.revokedAt?"Revoked":record.expiresAt<Date.now()?"Expired":"Active"}</small><h3>{record.email}</h3><p>Created {new Date(record.createdAt).toLocaleString()} · Expires {new Date(record.expiresAt).toLocaleString()}{record.lastUsedAt?` · Last used ${new Date(record.lastUsedAt).toLocaleString()}`:""}</p></div><div className="cms-actions">{!record.revokedAt&&record.expiresAt>Date.now()&&<><button className="ghost" onClick={()=>rotate(record)}>Replace link</button><button className="ghost danger" onClick={()=>revoke(record._id)}>Revoke</button></>}</div></article>)}</div>}</div></main>}
