import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  travelRequests: defineTable({ name: v.string(), email: v.string(), phone: v.optional(v.string()), contactPreference: v.optional(v.string()), bestTime: v.optional(v.string()), heardAbout: v.optional(v.string()), marketingOptIn: v.optional(v.boolean()), destination: v.string(), dates: v.optional(v.string()), travelers: v.string(), budget: v.optional(v.string()), tripType: v.string(), notes: v.optional(v.string()), advisorNotes: v.optional(v.string()), followUpAt: v.optional(v.number()), status: v.union(v.literal("new"), v.literal("contacted"), v.literal("quoted"), v.literal("booked"), v.literal("closed")), source: v.string(), createdAt: v.number(), updatedAt: v.optional(v.number()) }).index("by_status", ["status"]).index("by_createdAt", ["createdAt"]).index("by_followUpAt", ["followUpAt"]),
  promotions: defineTable({ title: v.string(), description: v.string(), destination: v.optional(v.string()), badge: v.optional(v.string()), ctaLabel: v.string(), active: v.boolean(), sortOrder: v.number(), createdAt: v.number(), updatedAt: v.optional(v.number()) }).index("by_active", ["active", "sortOrder"]),
  quotes: defineTable({ travelRequestId: v.id("travelRequests"), title: v.string(), summary: v.string(), amount: v.optional(v.number()), currency: v.string(), supplierName: v.optional(v.string()), supplierReference: v.optional(v.string()), expiresAt: v.optional(v.number()), status: v.union(v.literal("draft"), v.literal("sent"), v.literal("accepted"), v.literal("expired"), v.literal("declined")), travelerMessage: v.optional(v.string()), travelerRespondedAt: v.optional(v.number()), createdAt: v.number(), updatedAt: v.optional(v.number()) }).index("by_request", ["travelRequestId"]).index("by_status", ["status"]),
  supplierLinks: defineTable({ name: v.string(), category: v.string(), url: v.string(), notes: v.optional(v.string()), active: v.boolean(), createdAt: v.number(), updatedAt: v.optional(v.number()) }).index("by_active", ["active"]),
  savedTrips: defineTable({ accessCode: v.string(), email: v.string(), title: v.string(), destination: v.string(), tripType: v.string(), notes: v.optional(v.string()), createdAt: v.number(), updatedAt: v.optional(v.number()) }).index("by_accessCode", ["accessCode"]).index("by_email", ["email"]),
  portalAccess: defineTable({ email: v.string(), tokenHash: v.string(), travelRequestId: v.optional(v.id("travelRequests")), expiresAt: v.number(), revokedAt: v.optional(v.number()), createdAt: v.number(), lastUsedAt: v.optional(v.number()) }).index("by_tokenHash", ["tokenHash"]).index("by_email", ["email"]).index("by_request", ["travelRequestId"]),
  itineraries: defineTable({ travelRequestId: v.id("travelRequests"), title: v.string(), summary: v.string(), days: v.array(v.object({ day: v.number(), title: v.string(), details: v.string() })), published: v.boolean(), source: v.optional(v.union(v.literal("manual"), v.literal("draft-builder"), v.literal("ai"))), createdAt: v.number(), updatedAt: v.optional(v.number()) }).index("by_request", ["travelRequestId"]),
  notificationQueue: defineTable({ channel: v.union(v.literal("email"), v.literal("sms")), recipient: v.string(), subject: v.optional(v.string()), message: v.string(), status: v.union(v.literal("queued"), v.literal("sent"), v.literal("failed")), provider: v.optional(v.string()), providerMessageId: v.optional(v.string()), failureReason: v.optional(v.string()), relatedTravelRequestId: v.optional(v.id("travelRequests")), createdAt: v.number(), sentAt: v.optional(v.number()), updatedAt: v.optional(v.number()) }).index("by_status", ["status", "createdAt"]),
  analyticsEvents: defineTable({ event: v.string(), surface: v.string(), travelRequestId: v.optional(v.id("travelRequests")), quoteId: v.optional(v.id("quotes")), metadata: v.optional(v.string()), createdAt: v.number() }).index("by_createdAt", ["createdAt"]).index("by_event", ["event", "createdAt"]),
  adminSettings: defineTable({ key: v.string(), displayName: v.optional(v.string()), roleTitle: v.optional(v.string()), photo: v.optional(v.string()), theme: v.optional(v.string()), accent: v.optional(v.string()), density: v.optional(v.string()), landingPage: v.optional(v.string()), visibleMetrics: v.optional(v.array(v.string())), passcodeHash: v.optional(v.string()), passcodeSalt: v.optional(v.string()), passcodeUpdatedAt: v.optional(v.number()), updatedAt: v.number() }).index("by_key", ["key"]),
});
