"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";

type Day = { day: number; title: string; details: string };
type Itinerary = { _id?: string; title: string; summary: string; days: Day[]; published: boolean };
const empty: Itinerary = { title: "", summary: "", days: [{ day: 1, title: "Arrival", details: "" }], published: false };

export default function ItineraryAdminPage(){const[requestId,setRequestId]=useState("");const[token,setToken]=useState("");const[authorized,setAuthorized]=useState(false);const[itineraries,setItineraries]=useState<Itinerary[]>([]);const[form,setForm]=useState<Itinerary>(empty);const[message,setMessage]=useState("");
useEffect(()=>setRequestId(new URLSearchParams(window.location.search).get("requestId")||""),[]);
async function load(e?:FormEvent){e?.preventDefault();if(!requestId)return setMessage("Trip request ID is required.");const r=await fetch(`/api/admin/itineraries?requestId=${encodeURIComponent(requestId)}`,{headers:{"x-admin-token":token},cache:"no-store"});const d=await r.json();if(!r.ok){setAuthorized(false);return setMessage(d.error||"Unable to load itineraries.");}setAuthorized(true);setItineraries(d.itineraries??[]);setMessage("");}
async function save(e:FormEvent){e.preventDefault();const r=await fetch("/api/admin/itineraries",{method:"POST",headers:{"Content-Type":"application/json","x-admin-token":token},body:JSON.stringify({id:form._id,travelRequestId:requestId,...form})});const d=await r.json();if(!r.ok)return setMessage(d.error||"Unable to save itinerary.");setForm(empty);setMessage("Itinerary saved.");await load();}
function updateDay(index:number,patch:Partial<Day>){setForm(current=>({...current,days:current.days.map((day,i)=>i===index?{...day,...patch}:day)}));}
return <main className="admin-shell"><div className="shell"><div className="admin-header"><div><Link href="/admin" className="back-link">← Trip inquiries</Link><span className="eyebrow">Traveler itinerary</span><h1>Itinerary publisher</h1></div></div>{!authorized?<form className="admin-login" onSubmit={load}><h2>Open trip itinerary</h2><label>Trip request ID<input value={requestId} onChange={e=>setRequestId(e.target.value)} required/></label><input type="password" value={token} onChange={e=>setToken(e.target.value)} placeholder="Admin passcode" required/><button className="button">Open itinerary workspace</button>{message&&<p className="error">{message}</p>}</form>:<><form className="cms-form" onSubmit={save}><h2>{form._id?"Edit itinerary":"Create itinerary"}</h2><label>Title<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} required/></label><label className="check-label"><input type="checkbox" checked={form.published} onChange={e=>setForm({...form,published:e.target.checked})}/> Visible in traveler portal</label><label className="wide">Summary<textarea value={form.summary} onChange={e=>setForm({...form,summary:e.target.value})} required/></label><div className="wide itinerary-editor">{form.days.map((day,index)=><div className="itinerary-editor-day" key={index}><b>Day {index+1}</b><input value={day.title} onChange={e=>updateDay(index,{day:index+1,title:e.target.value})} placeholder="Day title"/><textarea value={day.details} onChange={e=>updateDay(index,{day:index+1,details:e.target.value})} placeholder="Flights, hotel, activities, notes…"/></div>)}</div><div className="wide cms-actions"><button type="button" className="ghost" onClick={()=>setForm(current=>({...current,days:[...current.days,{day:current.days.length+1,title:"",details:""}]}))}>Add day</button><button className="button">Save itinerary</button></div>{message&&<p className="success wide">{message}</p>}</form><div className="cms-list">{itineraries.map(item=><article key={item._id}><div><small>{item.published?"Published":"Draft"}</small><h3>{item.title}</h3><p>{item.summary}</p></div><button className="ghost" onClick={()=>setForm(item)}>Edit</button></article>)}</div></>}</div></main>}
