"use client";

import { FormEvent, useState } from "react";
import Link from "next/link";

type Notification={_id:string;channel:"email"|"sms";recipient:string;subject?:string;message:string;status:"queued"|"sent"|"failed";provider?:string;failureReason?:string;createdAt:number;sentAt?:number;relatedTravelRequestId?:string};

export default function NotificationsPage(){const[token,setToken]=useState("");const[authorized,setAuthorized]=useState(false);const[items,setItems]=useState<Notification[]>([]);const[message,setMessage]=useState("");const[form,setForm]=useState({channel:"email" as "email"|"sms",recipient:"",subject:"",message:"",relatedTravelRequestId:""});
async function load(e?:FormEvent){e?.preventDefault();const r=await fetch("/api/admin/notifications",{headers:{"x-admin-token":token},cache:"no-store"});const d=await r.json();if(!r.ok){setAuthorized(false);return setMessage(d.error||"Unable to open notifications.");}setAuthorized(true);setItems(d.notifications??[]);setMessage("");}
async function queue(e:FormEvent){e.preventDefault();const r=await fetch("/api/admin/notifications",{method:"POST",headers:{"Content-Type":"application/json","x-admin-token":token},body:JSON.stringify({...form,relatedTravelRequestId:form.relatedTravelRequestId||undefined})});const d=await r.json();if(!r.ok)return setMessage(d.error||"Unable to queue notification.");setForm({channel:"email",recipient:"",subject:"",message:"",relatedTravelRequestId:""});setMessage("Notification queued.");await load();}
async function send(item:Notification){setMessage("");const r=await fetch("/api/admin/notifications",{method:"PATCH",headers:{"Content-Type":"application/json","x-admin-token":token},body:JSON.stringify(item)});const d=await r.json();if(!r.ok)setMessage(d.error||"Unable to deliver notification.");else setMessage("Notification sent through configured delivery webhook.");await load();}
return <main className="admin-shell"><div className="shell"><div className="admin-header"><div><Link href="/admin/overview" className="back-link">← Dashboard</Link><span className="eyebrow">Outbound communication</span><h1>Notification center</h1></div></div>{!authorized?<form className="admin-login" onSubmit={load}><h2>Advisor access</h2><input type="password" value={token} onChange={e=>setToken(e.target.value)} placeholder="Admin passcode" required/><button className="button">Open notification center</button>{message&&<p className="error">{message}</p>}</form>:<><form className="cms-form" onSubmit={queue}><h2>Queue a traveler message</h2><label>Channel<select value={form.channel} onChange={e=>setForm({...form,channel:e.target.value as "email"|"sms"})}><option value="email">Email</option><option value="sms">SMS</option></select></label><label>Recipient<input value={form.recipient} onChange={e=>setForm({...form,recipient:e.target.value)} placeholder={form.channel==="email"?"traveler@example.com":"+15555555555"} required/></label><label>Subject<input value={form.subject} onChange={e=>setForm({...form,subject:e.target.value)} disabled={form.channel==="sms"}/></label><label>Trip request ID<input value={form.relatedTravelRequestId} onChange={e=>setForm({...form,relatedTravelRequestId:e.target.value)} placeholder="Optional"/></label><label className="wide">Message<textarea value={form.message} onChange={e=>setForm({...form,message:e.target.value)} required/></label><button className="button wide">Queue notification</button>{message&&<p className="wide success">{message}</p>}</form><div className="notification-list">{items.length?items.map(item=><article key={item._id}><div><small>{item.channel} · {new Date(item.createdAt).toLocaleString()}</small><h3>{item.recipient}</h3>{item.subject&&<b>{item.subject}</b>}<p>{item.message}</p>{item.failureReason&&<span className="error">{item.failureReason}</span>}</div><div className="notification-actions"><span className={`status-pill ${item.status}`}>{item.status}</span>{item.status!=="sent"&&<button className="ghost" onClick={()=>send(item)}>Send now</button>}</div></article>):<div className="empty-state"><h2>No notifications yet.</h2><p>Queue the first traveler message above.</p></div>}</div></>}</div></main>}
