// Curated travel library. Amazon links are Associates search links (tag erictomchik-20)
// so they always land on the current in-print edition instead of a dead ASIN.
export const AMAZON_TAG = "erictomchik-20";

export type Book = {
  slug: string;
  title: string;
  author: string;
  category: BookCategory;
  note: string;
  cover: string;
  year?: number;
};

export const BOOK_CATEGORIES = ["Inspiration", "Travel writing", "Food & culture", "Photography", "Practical", "Reference"] as const;
export type BookCategory = (typeof BOOK_CATEGORIES)[number];

export function amazonLink(book: Book): string {
  const q = encodeURIComponent(`${book.title} ${book.author}`);
  return `https://www.amazon.com/s?k=${q}&i=stripbooks&tag=${AMAZON_TAG}`;
}

export const BOOKS: Book[] = [
  {
    slug: "1000-places",
    title: "1,000 Places to See Before You Die",
    author: "Patricia Schultz",
    category: "Inspiration",
    note: "The original bucket-list book. Big, browsable, and still one of the best ways to find the trip you didn't know you wanted.",
    cover: "/books/1000-places.webp",
    year: 2000,
  },
  {
    slug: "amazing-train-journeys",
    title: "Amazing Train Journeys",
    author: "Lonely Planet",
    category: "Inspiration",
    note: "60 of the world's great rail trips, with practical notes. My go-to for slow, scenic itineraries.",
    cover: "/books/amazing-train-journeys.webp",
    year: 2018,
  },
  {
    slug: "atlas-obscura",
    title: "Atlas Obscura",
    author: "Joshua Foer, Dylan Thuras & Ella Morton",
    category: "Inspiration",
    note: "A guide to the world's strangest wonders. Perfect if your ideal trip has one thing in it nobody back home has heard of.",
    cover: "/books/atlas-obscura.webp",
    year: 2016,
  },
  {
    slug: "destinations-of-a-lifetime",
    title: "Destinations of a Lifetime",
    author: "National Geographic",
    category: "Inspiration",
    note: "225 of the most beautiful places on earth, photographed properly. Coffee-table fuel for the next big trip.",
    cover: "/books/destinations-of-a-lifetime.webp",
    year: 2015,
  },
  {
    slug: "epic-drives-of-the-world",
    title: "Epic Drives of the World",
    author: "Lonely Planet",
    category: "Inspiration",
    note: "50 legendary road trips with routes and timings. Ideal if you'd rather drive it than fly over it.",
    cover: "/books/epic-drives-of-the-world.webp",
    year: 2017,
  },
  {
    slug: "journeys-of-a-lifetime",
    title: "Journeys of a Lifetime",
    author: "National Geographic",
    category: "Inspiration",
    note: "500 of the world's greatest trips, sorted by mood and mode of travel. A great place to start a wish list.",
    cover: "/books/journeys-of-a-lifetime.webp",
    year: 2007,
  },
  {
    slug: "the-worlds-most-amazing-places",
    title: "Secret Journeys of a Lifetime",
    author: "National Geographic",
    category: "Inspiration",
    note: "500 hidden travel gems, away from the queues. Where I go looking when a client says 'somewhere different'.",
    cover: "/books/the-worlds-most-amazing-places.webp",
    year: 2016,
  },
  {
    slug: "the-travel-book",
    title: "The Travel Book",
    author: "Lonely Planet",
    category: "Inspiration",
    note: "Every country on earth, one spread each. The best browse in travel publishing.",
    cover: "/books/the-travel-book.webp",
    year: 2011,
  },
  {
    slug: "where-to-go-when",
    title: "Where to Go When: The Americas",
    author: "DK Eyewitness",
    category: "Inspiration",
    note: "Destinations organised by month. The single most useful way to plan around the calendar you actually have.",
    cover: "/books/where-to-go-when.webp",
    year: 2016,
  },
  {
    slug: "a-cooks-tour",
    title: "A Cook's Tour",
    author: "Anthony Bourdain",
    category: "Travel writing",
    note: "Bourdain circles the globe looking for the perfect meal. Great destination ideas hidden inside great storytelling.",
    cover: "/books/a-cooks-tour.webp",
    year: 2001,
  },
  {
    slug: "a-time-of-gifts",
    title: "A Time of Gifts",
    author: "Patrick Leigh Fermor",
    category: "Travel writing",
    note: "An eighteen-year-old walks across 1930s Europe. Some of the finest prose in travel writing.",
    cover: "/books/a-time-of-gifts.webp",
    year: 1977,
  },
  {
    slug: "a-walk-in-the-woods",
    title: "A Walk in the Woods",
    author: "Bill Bryson",
    category: "Travel writing",
    note: "The Appalachian Trail, attempted badly and written brilliantly. The best argument for trips that don't go to plan.",
    cover: "/books/a-walk-in-the-woods.webp",
    year: 1997,
  },
  {
    slug: "a-year-in-provence",
    title: "A Year in Provence",
    author: "Peter Mayle",
    category: "Travel writing",
    note: "Twelve months of markets, neighbours and long lunches in the south of France. Pure escapism.",
    cover: "/books/a-year-in-provence.webp",
    year: 1989,
  },
  {
    slug: "blue-highways",
    title: "Blue Highways",
    author: "William Least Heat-Moon",
    category: "Travel writing",
    note: "Small-town America by back roads only. The gold standard for the great American road trip.",
    cover: "/books/blue-highways.webp",
    year: 1981,
  },
  {
    slug: "eat-pray-love",
    title: "Eat, Pray, Love",
    author: "Elizabeth Gilbert",
    category: "Travel writing",
    note: "Italy, India and Bali as one long reset. Say what you like about it — it still sends people on the trip.",
    cover: "/books/eat-pray-love.webp",
    year: 2001,
  },
  {
    slug: "in-patagonia",
    title: "In Patagonia",
    author: "Bruce Chatwin",
    category: "Travel writing",
    note: "Fragments and encounters at the end of the world. The book that put Patagonia on so many lists.",
    cover: "/books/in-patagonia.webp",
    year: 1977,
  },
  {
    slug: "in-a-sunburned-country",
    title: "In a Sunburned Country",
    author: "Bill Bryson",
    category: "Travel writing",
    note: "Bryson on Australia — funny, affectionate and full of detail. Read it and you'll want to go.",
    cover: "/books/in-a-sunburned-country.webp",
    year: 2000,
  },
  {
    slug: "into-thin-air",
    title: "Into Thin Air",
    author: "Jon Krakauer",
    category: "Travel writing",
    note: "The 1996 Everest disaster, first-hand. Gripping, and a sober look at what ambition costs at altitude.",
    cover: "/books/into-thin-air.webp",
    year: 1996,
  },
  {
    slug: "kitchen-confidential",
    title: "Kitchen Confidential",
    author: "Anthony Bourdain",
    category: "Travel writing",
    note: "Where Bourdain started. Worth reading before any trip planned around what you're going to eat.",
    cover: "/books/kitchen-confidential.webp",
    year: 2000,
  },
  {
    slug: "neither-here-nor-there",
    title: "Neither Here Nor There: Travels in Europe",
    author: "Bill Bryson",
    category: "Travel writing",
    note: "A backpacking loop through Europe revisited decades later. Sharp on why the same city hits differently at different ages.",
    cover: "/books/neither-here-nor-there.webp",
    year: 1991,
  },
  {
    slug: "notes-from-a-small-island",
    title: "Notes from a Small Island",
    author: "Bill Bryson",
    category: "Travel writing",
    note: "A farewell tour of Britain, town by town. The best primer before a UK trip.",
    cover: "/books/notes-from-a-small-island.webp",
    year: 1995,
  },
  {
    slug: "on-the-road",
    title: "On the Road",
    author: "Jack Kerouac",
    category: "Travel writing",
    note: "The book that convinced a generation to just go. Messy, restless and impossible to sit still through.",
    cover: "/books/on-the-road.webp",
    year: 1957,
  },
  {
    slug: "out-of-africa",
    title: "Out of Africa",
    author: "Isak Dinesen",
    category: "Travel writing",
    note: "A coffee farm at the foot of the Ngong Hills. Essential before a safari.",
    cover: "/books/out-of-africa.webp",
    year: 1937,
  },
  {
    slug: "seven-years-in-tibet",
    title: "Seven Years in Tibet",
    author: "Heinrich Harrer",
    category: "Travel writing",
    note: "An escape across the Himalaya into old Lhasa. A true story that reads like fiction.",
    cover: "/books/seven-years-in-tibet.webp",
    year: 1953,
  },
  {
    slug: "the-art-of-travel",
    title: "The Art of Travel",
    author: "Alain de Botton",
    category: "Travel writing",
    note: "Why we travel, and why the reality rarely matches the daydream. Short, and it will change how you plan.",
    cover: "/books/the-art-of-travel.webp",
    year: 2002,
  },
  {
    slug: "the-geography-of-bliss",
    title: "The Geography of Bliss",
    author: "Eric Weiner",
    category: "Travel writing",
    note: "One grump tours the world's happiest countries. Funny, and a genuinely different way to pick a destination.",
    cover: "/books/the-geography-of-bliss.webp",
    year: 2008,
  },
  {
    slug: "the-great-railway-bazaar",
    title: "The Great Railway Bazaar",
    author: "Paul Theroux",
    category: "Travel writing",
    note: "London to Asia and back entirely by train. The book that made rail travel romantic again.",
    cover: "/books/the-great-railway-bazaar.webp",
    year: 1975,
  },
  {
    slug: "the-lost-city-of-z",
    title: "The Lost City of Z",
    author: "David Grann",
    category: "Travel writing",
    note: "An Amazon obsession and a vanished explorer. Adventure reading of the highest order.",
    cover: "/books/the-lost-city-of-z.webp",
    year: 2000,
  },
  {
    slug: "the-old-patagonian-express",
    title: "The Old Patagonian Express",
    author: "Paul Theroux",
    category: "Travel writing",
    note: "Boston to Patagonia by train, the long way. A masterclass in slow travel.",
    cover: "/books/the-old-patagonian-express.webp",
    year: 1979,
  },
  {
    slug: "the-places-in-between",
    title: "The Places in Between",
    author: "Rory Stewart",
    category: "Travel writing",
    note: "Walking across Afghanistan in 2002, village to village. Remarkable on the kindness of strangers.",
    cover: "/books/the-places-in-between.webp",
    year: 1970,
  },
  {
    slug: "the-snow-leopard",
    title: "The Snow Leopard",
    author: "Peter Matthiessen",
    category: "Travel writing",
    note: "A Himalayan trek in search of an animal that may never appear. Quiet, and one of the greats.",
    cover: "/books/the-snow-leopard.webp",
    year: 1978,
  },
  {
    slug: "the-sun-also-rises",
    title: "The Sun Also Rises",
    author: "Ernest Hemingway",
    category: "Travel writing",
    note: "Paris and Pamplona in the 1920s. Reads like the original case for going somewhere for the festival.",
    cover: "/books/the-sun-also-rises.webp",
    year: 1926,
  },
  {
    slug: "tracks",
    title: "Tracks",
    author: "Robyn Davidson",
    category: "Travel writing",
    note: "1,700 miles across Australia with four camels and a dog. Extraordinary solo travel writing.",
    cover: "/books/tracks.webp",
    year: 1980,
  },
  {
    slug: "travels-with-charley",
    title: "Travels with Charley",
    author: "John Steinbeck",
    category: "Travel writing",
    note: "Steinbeck and his dog drive across America. Still the warmest book about seeing your own country.",
    cover: "/books/travels-with-charley.webp",
    year: 1962,
  },
  {
    slug: "turn-right-at-machu-picchu",
    title: "Turn Right at Machu Picchu",
    author: "Mark Adams",
    category: "Travel writing",
    note: "Retracing the route to Machu Picchu a century on. Read it before you book Peru.",
    cover: "/books/turn-right-at-machu-picchu.webp",
    year: 2011,
  },
  {
    slug: "under-the-tuscan-sun",
    title: "Under the Tuscan Sun",
    author: "Frances Mayes",
    category: "Travel writing",
    note: "A crumbling villa, a Tuscan summer, and a lot of very good food. Dangerous for anyone weighing up Italy.",
    cover: "/books/under-the-tuscan-sun.webp",
    year: 1996,
  },
  {
    slug: "west-with-the-night",
    title: "West with the Night",
    author: "Beryl Markham",
    category: "Travel writing",
    note: "Flying and horse training in colonial Kenya. Hemingway thought it was better than anything he'd written.",
    cover: "/books/west-with-the-night.webp",
    year: 1942,
  },
  {
    slug: "wild",
    title: "Wild: From Lost to Found on the Pacific Crest Trail",
    author: "Cheryl Strayed",
    category: "Travel writing",
    note: "1,100 miles alone on the PCT. Less a hiking book than a reminder of what travel can do for you.",
    cover: "/books/wild.webp",
    year: 1767,
  },
  {
    slug: "a-moveable-feast",
    title: "A Moveable Feast",
    author: "Ernest Hemingway",
    category: "Food & culture",
    note: "Paris in the twenties, café by café. Short, and it makes a first trip to Paris feel bigger.",
    cover: "/books/a-moveable-feast.webp",
    year: 1964,
  },
  {
    slug: "salt-fat-acid-heat",
    title: "Salt, Fat, Acid, Heat",
    author: "Samin Nosrat",
    category: "Food & culture",
    note: "Not a travel book, but it will teach you what you're tasting abroad — and how to cook it when you're home.",
    cover: "/books/salt-fat-acid-heat.webp",
    year: 2017,
  },
  {
    slug: "the-food-lovers-guide-to-paris",
    title: "The Food Lover's Guide to Paris",
    author: "Patricia Wells",
    category: "Food & culture",
    note: "Bakeries, bistros and markets from someone who knows Paris block by block. Take it with you.",
    cover: "/books/the-food-lovers-guide-to-paris.webp",
    year: 1984,
  },
  {
    slug: "the-worlds-best-street-food",
    title: "The World's Best Street Food",
    author: "Lonely Planet",
    category: "Food & culture",
    note: "100 street dishes, where to find them and how to make them. Snackable planning.",
    cover: "/books/the-worlds-best-street-food.webp",
    year: 2016,
  },
  {
    slug: "world-travel-an-irreverent-guide",
    title: "World Travel: An Irreverent Guide",
    author: "Anthony Bourdain & Laurie Woolever",
    category: "Food & culture",
    note: "Bourdain's own shortlist of where to go and what to eat there. My favourite gift for a new traveller.",
    cover: "/books/world-travel-an-irreverent-guide.webp",
    year: 2020,
  },
  {
    slug: "humans-of-new-york",
    title: "Humans of New York",
    author: "Brandon Stanton",
    category: "Photography",
    note: "Street portraits and short confessions from one city. Proof you don't have to go far for a great story.",
    cover: "/books/humans-of-new-york.webp",
    year: 2013,
  },
  {
    slug: "the-atlas-of-beauty",
    title: "The Atlas of Beauty",
    author: "Mihaela Noroc",
    category: "Photography",
    note: "Portraits of women in 50 countries. A reminder that the best part of travel is usually the people.",
    cover: "/books/the-atlas-of-beauty.webp",
    year: 2017,
  },
  {
    slug: "how-to-travel-the-world-on-50",
    title: "How to Travel the World on $50 a Day",
    author: "Matt Kepnes",
    category: "Practical",
    note: "Budget travel done properly. Even on a luxury trip, some of these habits are worth stealing.",
    cover: "/books/how-to-travel-the-world-on-50.webp",
    year: 2013,
  },
  {
    slug: "the-art-of-stillness",
    title: "The Art of Stillness",
    author: "Pico Iyer",
    category: "Practical",
    note: "A short book on going nowhere, by a man who has been everywhere. A good corrective if your itinerary is too full.",
    cover: "/books/the-art-of-stillness.webp",
    year: 2014,
  },
  {
    slug: "travel-with-children",
    title: "Travel with Children",
    author: "Lonely Planet",
    category: "Practical",
    note: "Family travel that doesn't feel like a compromise. Ages, destinations and honest logistics.",
    cover: "/books/travel-with-children.webp",
    year: 2015,
  },
  {
    slug: "vagabonding",
    title: "Vagabonding",
    author: "Rolf Potts",
    category: "Practical",
    note: "The classic on taking long trips without wrecking your life. Practical, calm and quietly persuasive.",
    cover: "/books/vagabonding.webp",
    year: 2002,
  },
  {
    slug: "national-geographic-atlas-of-the-world",
    title: "National Geographic Atlas of the World",
    author: "National Geographic",
    category: "Reference",
    note: "The reference atlas. Still the best way to plan a big trip with the whole map in front of you.",
    cover: "/books/national-geographic-atlas-of-the-world.webp",
    year: 1970,
  },
];

export function booksByCategory(): { category: BookCategory; books: Book[] }[] {
  return BOOK_CATEGORIES.map((category) => ({
    category,
    books: BOOKS.filter((b) => b.category === category),
  })).filter((g) => g.books.length > 0);
}
