"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { hasAdminSession } from "@/lib/adminClient";

type Supplier = { _id?: string; name: string; category: string; url: string; notes: string; active: boolean };
const empty: Supplier = { name: "", category: "Hotel / Resort", url: "", notes: "", active: true };

export default function SuppliersPage() {
  const [token,setToken]=useState(""); const [authorized,setAuthorized]=useState(false); const [checking,setChecking]=useState(true); const [suppliers,setSuppliers]=useState<Supplier[]>([]); const [form,setForm]=useState<Supplier>(empty); const [message,setMessage]=useState("");
  function authHeaders(json=false){return {...(json?{"Content-Type":"application/json"}:{}),...(token?{"x-admin-token":token}:{})};}
  async function load(e?:FormEvent){e?.preventDefault();const r=await fetch("/api/admin/suppliers",{headers:authHeaders(),cache:"no-store"});if(!r.ok){setAuthorized(false);return setMessage("Unable to open supplier resources.");}const d=await r.json();setAuthorized(true);setSuppliers(d.suppliers??[]);setMessage("");}
  useEffect(()=>{hasAdminSession().then(async ok=>{if(ok)await load();setChecking(false);});},[]);
  async function save(e:FormEvent){e.preventDefault();const r=await fetch("/api/admin/suppliers",{method:"POST",headers:authHeaders(true),body:JSON.stringify(form)});if(!r.ok)return setMessage("Unable to save supplier resource.");setForm(empty);setMessage("Supplier resource saved.");await load();}
  return <main className="admin-shell"><div className="shell"><div className="admin-header"><div><Link href="/admin/overview" className="back-link">← Dashboard</Link><span className="eyebrow">Advisor resources</span><h1>Supplier links</h1></div></div>
    {checking?<div className="admin-login"><h2>Checking advisor session…</h2></div>:!authorized?<form className="admin-login" onSubmit={load}><h2>Advisor access</h2><Link className="button" href="/admin/login">Secure sign in</Link><input type="password" value={token} onChange={e=>setToken(e.target.value)} placeholder="Legacy admin passcode"/><button className="ghost">Open with passcode</button>{message&&<p className="error">{message}</p>}</form>:<><form className="cms-form" onSubmit={save}><h2>{form._id?"Edit resource":"Add supplier resource"}</h2><label>Name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></label><label>Category<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option>Hotel / Resort</option><option>Cruise</option><option>Air</option><option>Package</option><option>Tour / Activity</option><option>Insurance</option><option>Other</option></select></label><label className="wide">Supplier or advisor URL<input type="url" value={form.url} onChange={e=>setForm({...form,url:e.target.value})} placeholder="https://" required/></label><label className="wide">Private notes<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><label className="check-label"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/> Active resource</label><div className="wide cms-actions"><button className="button">Save resource</button>{form._id&&<button className="ghost" type="button" onClick={()=>setForm(empty)}>Cancel</button>}</div>{message&&<p className="success wide">{message}</p>}</form><div className="cms-list">{suppliers.map(s=><article key={s._id}><div><small>{s.active?"Active":"Inactive"} · {s.category}</small><h3>{s.name}</h3><p>{s.notes||s.url}</p></div><div className="cms-actions"><a className="ghost" href={s.url} target="_blank" rel="noreferrer">Open</a><button className="ghost" onClick={()=>setForm({...s,notes:s.notes||""})}>Edit</button></div></article>)}</div></>}
  </div></main>;
}
