"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";

type Quote={_id:string;title:string;summary:string;amount?:number;currency:string;supplierName?:string;supplierReference?:string;expiresAt?:number;status:"draft"|"sent"|"accepted"|"expired"|"declined";createdAt:number};
const statuses:Quote["status"][]=["draft","sent","accepted","expired","declined"];
export default function QuotesPage(){const [requestId,setRequestId]=useState("");const [token,setToken]=useState("");const [quotes,setQuotes]=useState<Quote[]>([]);const [authorized,setAuthorized]=useState(false);const [message,setMessage]=useState("");const [form,setForm]=useState({title:"",summary:"",amount:"",currency:"USD",supplierName:"",supplierReference:"",expiresAt:""});
useEffect(()=>{setRequestId(new URLSearchParams(window.location.search).get("requestId")||"");},[]);
async function load(e?:FormEvent){e?.preventDefault();if(!requestId)return setMessage("Open this page from a trip inquiry or provide a requestId.");const r=await fetch(`/api/admin/quotes?requestId=${encodeURIComponent(requestId)}`,{headers:{"x-admin-token":token},cache:"no-store"});if(!r.ok){setAuthorized(false);return setMessage("Unable to open quote workspace.");}const d=await r.json();setAuthorized(true);setQuotes(d.quotes??[]);setMessage("");}
async function createQuote(e:FormEvent){e.preventDefault();const r=await fetch("/api/admin/quotes",{method:"POST",headers:{"Content-Type":"application/json","x-admin-token":token},body:JSON.stringify({travelRequestId:requestId,...form,amount:form.amount?Number(form.amount):undefined,expiresAt:form.expiresAt?new Date(`${form.expiresAt}T23:59:59`).getTime():undefined})});if(!r.ok)return setMessage("Unable to create quote.");setForm({title:"",summary:"",amount:"",currency:"USD",supplierName:"",supplierReference:"",expiresAt:""});setMessage("Quote created as draft.");await load();}
async function setStatus(id:string,status:Quote["status"]){const r=await fetch("/api/admin/quotes",{method:"PATCH",headers:{"Content-Type":"application/json","x-admin-token":token},body:JSON.stringify({id,status})});if(r.ok)setQuotes(q=>q.map(x=>x._id===id?{...x,status}:x));else setMessage("Unable to update quote.");}
return <main className="admin-shell"><div className="shell"><div className="admin-header"><div><Link href="/admin" className="back-link">← Trip inquiries</Link><span className="eyebrow">Advisor quoting</span><h1>Quote workspace</h1></div></div>{!authorized?<form className="admin-login" onSubmit={load}><h2>Open quote workspace</h2><label>Trip request ID<input value={requestId} onChange={e=>setRequestId(e.target.value)} required/></label><input type="password" value={token} onChange={e=>setToken(e.target.value)} placeholder="Admin passcode" required/><button className="button">Open quotes</button>{message&&<p className="error">{message}</p>}</form>:<><form className="cms-form" onSubmit={createQuote}><h2>Create quote</h2><label>Quote title<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} required/></label><label>Supplier<input value={form.supplierName} onChange={e=>setForm({...form,supplierName:e.target.value})}/></label><label className="wide">Summary<textarea value={form.summary} onChange={e=>setForm({...form,summary:e.target.value})} required/></label><label>Amount<input type="number" step="0.01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label><label>Currency<input value={form.currency} onChange={e=>setForm({...form,currency:e.target.value})}/></label><label>Supplier reference<input value={form.supplierReference} onChange={e=>setForm({...form,supplierReference:e.target.value})}/></label><label>Expires<input type="date" value={form.expiresAt} onChange={e=>setForm({...form,expiresAt:e.target.value})}/></label><button className="button wide">Save draft quote</button>{message&&<p className="success wide">{message}</p>}</form><div className="quote-list">{quotes.length?quotes.map(q=><article className="quote-card" key={q._id}><div><small>{new Date(q.createdAt).toLocaleDateString()}</small><h2>{q.title}</h2><p>{q.summary}</p>{q.amount!==undefined&&<b>{new Intl.NumberFormat("en-US",{style:"currency",currency:q.currency||"USD"}).format(q.amount)}</b>}<span>{q.supplierName||"Supplier not recorded"}{q.supplierReference?` · ${q.supplierReference}`:""}</span></div><select value={q.status} onChange={e=>setStatus(q._id,e.target.value as Quote["status"])}>{statuses.map(s=><option key={s}>{s}</option>)}</select></article>):<div className="empty-state"><h2>No quotes yet.</h2><p>Create the first draft above.</p></div>}</div></>}</div></main>}
